import type { Task } from './types';

export const seedTasks: Task[] = [
  {
    id: 't1',
    title: 'Set up Next.js (App Router)',
    description: 'Initialize project with Tailwind + TS.',
    status: 'scheduled',
    assignee: 'Alice',
    tags: ['setup', 'nextjs'],
    createdAt: '2025-09-01T10:00:00.000Z',
    priority: 'medium',
  },
  {
    id: 't2',
    title: 'Design Kanban columns',
    description: 'Scheduled / In Progress / Done',
    status: 'scheduled',
    assignee: 'Bob',
    tags: ['ux'],
    createdAt: '2025-09-01T10:05:00.000Z',
  },
  {
    id: 't3',
    title: 'Task card component',
    description: 'Title, tags, assignee, menu.',
    status: 'in-progress',
    assignee: 'Alice',
    tags: ['ui', 'components'],
    createdAt: '2025-09-02T09:00:00.000Z',
    priority: 'high',
  },
  {
    id: 't4',
    title: 'Drag & Drop (nice to have)',
    description: 'Reorder & move between columns.',
    status: 'scheduled',
    assignee: 'Cara',
    tags: ['dnd'],
    createdAt: '2025-09-02T09:30:00.000Z',
  },
  {
    id: 't5',
    title: 'Filter by tag/assignee/text',
    description: 'Clientside search + chips.',
    status: 'in-progress',
    assignee: 'Dan',
    tags: ['filters'],
    createdAt: '2025-09-02T12:00:00.000Z',
  },
  {
    id: 't6',
    title: 'Create task modal',
    description: 'Form with validation.',
    status: 'scheduled',
    assignee: 'Alice',
    tags: ['crud', 'form'],
    createdAt: '2025-09-03T08:00:00.000Z',
  },
  {
    id: 't7',
    title: 'Update task',
    description: 'Edit title/assignee/tags.',
    status: 'scheduled',
    assignee: 'Bob',
    tags: ['crud'],
    createdAt: '2025-09-03T08:10:00.000Z',
  },
  {
    id: 't8',
    title: 'Delete task',
    description: 'Confirm dialog + toast.',
    status: 'scheduled',
    assignee: 'Cara',
    tags: ['crud'],
    createdAt: '2025-09-03T08:20:00.000Z',
  },
  {
    id: 't9',
    title: 'Task detail route',
    description: '/tasks/[id] full view.',
    status: 'scheduled',
    assignee: 'Dan',
    tags: ['routing'],
    createdAt: '2025-09-03T09:00:00.000Z',
  },
  {
    id: 't10',
    title: 'Empty/loading/error states',
    description: 'Meaningful UX.',
    status: 'done',
    assignee: 'Alice',
    tags: ['ux'],
    createdAt: '2025-09-01T11:00:00.000Z',
  },
  {
    id: 't11',
    title: 'Responsive layout',
    description: 'Mobile-first columns.',
    status: 'done',
    assignee: 'Bob',
    tags: ['responsive'],
    createdAt: '2025-09-01T12:00:00.000Z',
  },
  {
    id: 't12',
    title: 'Persist filters (nice)',
    description: 'Save to localStorage.',
    status: 'scheduled',
    assignee: 'Cara',
    tags: ['filters'],
    createdAt: '2025-09-04T08:00:00.000Z',
  },
];
